### ISSUE TITLE
streamlit.errors.StreamlitAPIException: Progress Value has invalid value [0.0, 1.0]: 1.001073

### ISSUE THREAD

**Issue by MiningIrving** [SUSTYuxiao/PdfTranslator#6]
The translation of the 43-page document reported an error at the end.
2024-11-24 16:43:36.099 Traceback (most recent call last):
  File "/home/mining/anaconda3/envs/translator/lib/python3.11/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/mining/data/translator/PdfTranslator/app/server.py", line 191, in <module>
    main()
  File "/home/mining/data/translator/PdfTranslator/app/server.py", line 170, in main
    docParser.doTrans(
  File "/home/mining/data/translator/PdfTranslator/app/translator/doc_parser.py", line 127, in doTrans
    self.process_all_paragraph(doc, False)
  File "/home/mining/data/translator/PdfTranslator/app/translator/doc_parser.py", line 75, in process_all_paragraph
    self.process_paragraph(paragraph,is_count_mode)
  File "/home/mining/data/translator/PdfTranslator/app/translator/doc_parser.py", line 61, in process_paragraph
    processed_text = self.process_text(paragraph.text,is_count_mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mining/data/translator/PdfTranslator/app/translator/doc_parser.py", line 39, in process_text
    self.progress.addCur()
  File "/home/mining/data/translator/PdfTranslator/app/translator/progress.py", line 17, in addCur
    self.progress_bar.progress(rate)
  File "/home/mining/anaconda3/envs/translator/lib/python3.11/site-packages/streamlit/elements/progress.py", line 53, in progress
    raise StreamlitAPIException(
streamlit.errors.StreamlitAPIException: Progress Value has invalid value [0.0, 1.0]: 1.001073

**Comment by MiningIrving** [comment]
Can an LLM be developed to write to the document immediately after reasoning, to avoid the issue of not saving the results after a large number of tokens have been wasted?

**Comment by MiningIrving** [comment]
For some unknown reason, the progress bar exceeds 1; changing it here to cap at 1 should resolve the issue. Additionally, the project's translation of the paper is not very effective, especially when it comes to format restoration. There are numerous positional deviations, and the spacing between lines of text is incorrect, resulting in overlapping.
